config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
        confirmations: 'confirmations'
    }
    root 'billboards#index', as: 'home'
    resources :billboards do
      resources :billboard_employments
      resources :comments
    end
    resource :profile
    namespace :admin do
      # member do
      get 'billboards'
      get 'users'
      patch 'appoint_admin'
      patch 'remove_admin'
      patch 'confirm'
      # end
    end
  end
end

app/views/admins/_requests.html.erb
<h3><%= t("admin.requests.head") %></h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("admin.requests.body") %></th>
    <th scope="col"><%= t("admin.requests.brand") %></th>
    <th scope="col"><%= t("admin.requests.start_date") %></th>
    <th scope="col"><%= t("admin.requests.duration") %></th>
    <th scope="col"><%= t("admin.requests.created_at") %></th>
    <th scope="col"><%= t("admin.requests.adv_type") %></th>
    <th scope="col"><%= t("admin.requests.active") %></th>
  </tr>
  </thead>
  <tbody>
  <% @requests.order('active DESC').each do |request| %>
    <tr id="request" class=<%= set_class(request.active) %>>
      <td>
        <%= request.body %>
      </td>
      <td>
        <%= request.brand %>
      </td>
      <td>
        <%= request.start_date %>
      </td>
      <td>
        <%= formatted_duration(request.duration) %>
      </td>
      <td>
        <%= formatted_date(request.created_at) %>
      </td>
      <td>
        <%= request.adv_type %>
      </td>
      <td>
        <% if request.active %>
          <%= link_to t("admin.requests.confirm"), confirm_admin_path(:request_id => request.id, :user_id => request.user_id),
                      method: :patch, style: 'color: green' %>

          </td>
          <td>
            <%= link_to t("admin.requests.reject"),
                        billboard_billboard_employment_path(:id => request.id,
                                                            :billboard_id => request.billboard_id,
                                                            :user_id => request.user_id),
                        {:style => 'color: red', :method => :delete,
                         data: {confirm: t("confirmation")}, class: "delete"} %>
        <% end %>
        </td>
        </tr>
  <% end %>
  </tbody>
</table>

app/views/admins/users.html.erb
<body>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("admin.users.full_name") %></th>
    <th scope="col"><%= t("admin.users.email") %></th>
    <th scope="col"><%= t("admin.users.count") %></th>
    <th scope="col"><%= t("admin.users.pay") %></th>
    <th scope="col"><%= t("admin.users.created_at") %></th>
    <th scope="col"><%= t("admin.users.admin") %></th>
  </tr>
  </thead>
  <tbody>
  <% @users.find_each do |user| %>
    <tr id="user">
      <td>
        <%= user.first_name %>
        <%= user.second_name %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= User.get_billboards_count(user.id) %>
      </td>
      <td>
        <%= User.get_pay_per_month(user.id) %>
      </td>
      <td>
        <%= formatted_date(user.created_at) %>
      </td>
      <td>
        <%= user.admin %>
      </td>
      <td>
        <%= link_to t("admin.users.appoint_admin"), appoint_admin_admin_path(:user_id => user.id), method: :patch %>
      </td>
      <td>
        <%= link_to t("admin.users.remove_admin"), remove_admin_admin_path(:user_id => user.id), method: :patch %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</body>