config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
        confirmations: 'confirmations'
    }
    root 'billboards#index', as: 'home'
    resources :billboards do
      resources :billboard_employments
      resources :comments
    end
    resource :profile
    namespace :admin do
      # member do
      get 'billboards'
      get 'users'
      patch 'appoint_admin'
      patch 'remove_admin'
      patch 'confirm'
      # end
    end
  end
end

app/views/admin/_billboards.html.erb
<h3><%= t("admin.billboards.head") %></h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("admin.billboards.address") %></th>
    <th scope="col"><%= t("admin.billboards.price") %></th>
    <th scope="col"><%= t("admin.billboards.use") %></th>
    <th scope="col"><%= t("admin.billboards.inactivity") %></th>
    <th scope="col"><%= t("admin.billboards.created_at") %></th>
  </tr>
  </thead>
  <tbody>
  <% @billboards.find_each do |billboard| %>
    <tr id="billboard">
      <td>
        <%= billboard.address %>
      </td>
      <td>
        <table class="table">
          <thead>
          <tr>
            <th scope="col"><%= t("admin.billboards.price") %></th>
            <th scope="col"><%= t("admin.billboards.updated_at") %></th>
          </tr>
          </thead>
          <tbody>
          <% Price.get_all_prices(billboard.id).each do |data| %>
            <tr >
              <td>
                <%= data["price"] %>
              </td>
              <td>
                <%= data["created_at"] %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </td>
      <td>
        <%= Billboard.get_days_of_use(billboard.id) %>
      </td>
      <td>
        <%= Billboard.get_days_of_inactivity(billboard.id) %>
      </td>
      <td>
        <%= formatted_date(billboard.created_at) %>
      </td>
      <td>
        <%= link_to t("admin.billboards.edit"), edit_billboard_path(:id => billboard.id), style: 'color: green' %>
      </td>
      <td>
        <%= link_to t("admin.billboards.delete"), billboard_path(:id => billboard.id),
                    {:style => 'color: red', :method => :delete,
                     data: {confirm: t("confirmation")}, class: "delete"} %>
      </td>
      <td>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/_requests.html.erb
<h3><%= t("admin.requests.head") %></h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("admin.requests.body") %></th>
    <th scope="col"><%= t("admin.requests.brand") %></th>
    <th scope="col"><%= t("admin.requests.start_date") %></th>
    <th scope="col"><%= t("admin.requests.duration") %></th>
    <th scope="col"><%= t("admin.requests.created_at") %></th>
    <th scope="col"><%= t("admin.requests.adv_type") %></th>
    <th scope="col"><%= t("admin.requests.active") %></th>
  </tr>
  </thead>
  <tbody>
  <% @requests.order('active DESC').each do |request| %>
    <tr id="request" class=<%= set_class(request.active) %>>
      <td>
        <%= request.body %>
      </td>
      <td>
        <%= request.brand %>
      </td>
      <td>
        <%= request.start_date %>
      </td>
      <td>
        <%= formatted_duration(request.duration) %>
      </td>
      <td>
        <%= formatted_date(request.created_at) %>
      </td>
      <td>
        <%= request.adv_type %>
      </td>
      <td>
        <% if request.active %>
          <%= link_to t("admin.requests.confirm"), admin_confirm_path(:request_id => request.id, :user_id => request.user_id),
                      method: :patch, style: 'color: green' %>

          </td>
          <td>
            <%= link_to t("admin.requests.reject"),
                        billboard_billboard_employment_path(:id => request.id,
                                                            :billboard_id => request.billboard_id,
                                                            :user_id => request.user_id),
                        {:style => 'color: red', :method => :delete,
                         data: {confirm: t("confirmation")}, class: "delete"} %>
        <% end %>
        </td>
        </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/billboards.html.erb
  <%= render "admin/billboards/requests" %>
  <hr>
  <%= render "admin/billboards/billboards" %>

app/views/admin/users.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("admin.users.full_name") %></th>
    <th scope="col"><%= t("admin.users.email") %></th>
    <th scope="col"><%= t("admin.users.count") %></th>
    <th scope="col"><%= t("admin.users.pay") %></th>
    <th scope="col"><%= t("admin.users.created_at") %></th>
    <th scope="col"><%= t("admin.users.admin") %></th>
  </tr>
  </thead>
  <tbody>
  <% @users.find_each do |user| %>
    <tr id="user">
      <td>
        <%= user.first_name %>
        <%= user.second_name %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= @billboards_in_use[user.id] %>
      </td>
      <td>
        <%= @pay_per_month[user.id] %>
      </td>
      <td>
        <%= formatted_date(user.created_at) %>
      </td>
      <td>
        <%= user.admin %>
      </td>
      <td>
        <%= link_to t("admin.users.appoint_admin"), admin_appoint_admin_path(:user_id => user.id), method: :patch %>
      </td>
      <td>
        <%= link_to t("admin.users.remove_admin"), admin_remove_admin_path(:user_id => user.id), method: :patch %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>