config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
        confirmations: 'confirmations'
    }
    root 'billboards#index', as: 'home'
    resources :billboards do
      resources :billboard_employments
      resources :comments
    end
    resource :profile
    namespace :admin do
      # member do
      get 'billboards'
      get 'users'
      patch 'appoint_admin'
      patch 'remove_admin'
      patch 'confirm'
      # end
    end
  end
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :billboard_employments
  has_many :comments, dependent: :destroy
  belongs_to :price, dependent: :destroy, optional: true, validate: true
  mount_uploader :photo, AvatarUploader
  geocoded_by :get_full_address
  validates :address, presence: true, length: {minimum: 5}
  after_validation :geocode

  def get_full_address
    [address, "Минск"].compact.join(', ')
  end

  def get_price
    # Find price for billboard
    Price.joins(:billboard).where(prices: {id: price_id})[0].price
  end

  def get_all_prices
    # Find all prices for all the time for billboard
    Price.joins(:billboard).where(prices: {billboard_id: id})
  end

  def self.get_days_of_use
    @days_of_use = Hash.new(0)
    BillboardEmployment.select(:id, :billboard_id, :start_date, :duration).find_each do |employment|
      end_date = employment.start_date + employment.duration.month
      if end_date <= Date.today
        @days_of_use[employment.billboard_id] += (end_date - employment.start_date).to_i
      elsif employment.start_date <= Date.today
        @days_of_use[employment.billboard_id] += (Date.today - employment.start_date).to_i
      else
        @days_of_use[employment.billboard_id] += 0
      end
    end
    return @days_of_use
  end

  def self.get_days_of_inactivity
    @days_of_inactivity = Hash.new(0)
    BillboardEmployment.select(:id, :billboard_id, :start_date, :duration, "billboards.created_at").
        joins(:billboard).find_each do |employment|
      @days_of_inactivity[employment.billboard_id] +=
          (Date.today - (employment.created_at.to_date + @days_of_use[employment.billboard_id])).to_i
    end
    return @days_of_inactivity
  end

  def self.get_free_billboards
    # Return the list of free billboards
    Billboard.select(:id, :address).joins(:billboard_employments).where("
    :date NOT BETWEEN start_date AND DATE_ADD(start_date,INTERVAL duration MONTH)",
                                                                        date: Date.today).group(:id, :address)
  end

  def self.get_release_date
    # Return date when billboard will become free
    @date = Hash.new(0)
    BillboardEmployment.select(:id, :billboard_id, :start_date, :duration).
        joins(:billboard).where.not(active: true).find_each do |employment|
      end_date = employment.start_date + employment.duration.month
      if end_date >= Date.today
        @date[employment.billboard_id] = end_date
      end
    end
    return @date
  end

  def self.set_price(billboard_id, price_id)
    record = Billboard.find billboard_id
    record.update(price_id: price_id)
  end

  def self.update_params
    # Update brand and adv_type of each billboard
    Billboard.connection.select_all(<<-SQL.squish)
      UPDATE billboards as b
      JOIN billboard_employments as be
        on be.billboard_id = b.id
      SET b.adv_type = IF(CURDATE() BETWEEN be.start_date AND DATE_ADD(be.start_date,INTERVAL be.duration MONTH),
        be.adv_type,null),
      b.brand = IF(CURDATE() BETWEEN be.start_date AND DATE_ADD(be.start_date,INTERVAL be.duration MONTH),
        be.brand,null);
    SQL
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :verify_user, except: [:show, :index]

  def show
  end

  def index
    @billboards = Billboard.all.order(params[:sort]).paginate(:per_page => 5, :page => params[:page])
    @free_billboards = Billboard.get_free_billboards
    @release_date = Billboard.get_release_date
  end

  def new
    @billboard = Billboard.new
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      @price = @billboard.create_price(price: params[:price][:price],billboard_id: @billboard.id)
      Billboard.set_price(@price.billboard_id, @price.id)
      redirect_to home_path
    else
      render "new"
    end
  end

  def edit
    @price = Price.find(@billboard.price_id)
  end

  def update
    if @billboard.update(billboard_params)
      @price = @billboard.create_price(price: params[:price][:price],billboard_id: @billboard.id)
      Billboard.set_price(@price.billboard_id, @price.id)
      redirect_to home_path
    else
      render "edit"
    end
  end

  def destroy
    @billboard.destroy
    redirect_to admin_billboards_path
  end

  def set_billboard
    @billboard = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:id,
                                      :photo,
                                      :address)
  end

  def price_params
    params.require(:price).permit(:price)
  end

  def verify_user
    unless current_user.admin
      redirect_to home_path
    end
  end

end

app/helpers/billboards_helper.rb
module BillboardsHelper
  def check_for_null(argument)
    if argument
      argument
    else
      t("billboard.index.none")
    end
  end

  def get_date(billboard)
    release_date = @release_date[billboard.id]
    unless @release_date[billboard.id] == 0
      release_date
    else
      t("billboard.index.vacant")
    end
  end
end

app/views/billboards/_billboard.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("billboard.show.address") %></th>
    <th scope="col"><%= t("billboard.show.price") %></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= billboard.address %></td>
    <td><%= billboard.get_price %></td>
  </tr>
  </tbody>
</table>

app/views/billboards/_billboards.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("billboard.index.address") %></th>
    <th scope="col"><%= t("billboard.index.price") %></th>
    <th scope="col"><%= link_to t("billboard.index.ad_type"), home_path(:sort => "adv_type DESC") %></th>
    <th scope="col"><%= link_to t("billboard.index.brand"), home_path(:sort => "brand DESC") %></th>
    <th scope="col"><%= t("billboard.index.release_date") %></th>
  </tr>
  </thead>
  <tbody>
  <% billboards.each do |billboard| %>
    <tr class="table-light">
      <td><%= billboard.address %></td>
      <td><%= billboard.get_price %></td>
      <td><%= check_for_null(billboard.adv_type) %></td>
      <td><%= check_for_null(billboard.brand) %></td>
      <td><%= @release_date[billboard.id] %></td>
      <td><%= link_to t("billboard.index.billboard_link"), billboard_path(billboard) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate billboards %>

app/views/billboards/_form.html.erb
<% if @billboard.errors.any? %>
  <% @billboard.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
  <% end %>
<% else %>
  <div class="col-7">
    <p>
      <%= t('billboard.new.address') %>
      <%= f.text_field(:address, {autofocus: true, :class => "form-control"}) %>
    </p>
    <p>
      <%= t('billboard.new.price') %>
      <%= fields_for :price do |price_form| %>
        <%= price_form.number_field :price, {:class => "form-control"}%>
      <% end %>
    </p>
    <hr>
    <div class="custom-file">
      <p>
        <%= f.file_field :photo, {:class => "custom-file-label", :placeholder => t("billboard.new.photo")} %>
      </p>
    </div>
    <hr>
    <p>
      <%= f.submit t('billboard.new.submit'), :class => "btn btn-success" %>
    </p>
  </div>
<% end %>

app/views/billboards/_free_billboards.html.erb
<h3><%= t("billboard.index.free") %></h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th scope="col"><%= t("billboard.index.address") %></th>
  </tr>
  </thead>
  <tbody>
  <% free_billboards.each do |billboard| %>
    <tr class="table-light">
      <td><%= billboard.address %></td>
      <td><%= link_to t("billboard.index.billboard_link"), billboard_path(billboard.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/billboards/edit.html.erb
<h2><%= t('billboard.edit.head') %></h2>
<%= form_for :billboard, html: {miltipart: true}, url: billboard_path, method: :patch do |f| %>
  <%= render partial: "form", locals: {f: f} %>
<% end %>

app/views/billboards/index.html.erb
  <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.map_key %>&callback=initMap">
  </script>
<!--The div element for the map -->
<div id="map"></div>
<div class="col-8">
  <%= render 'billboards', billboards: @billboards %>
  <%= render 'free_billboards', free_billboards: @free_billboards %>
</div>

app/views/billboards/new.html.erb
<h2><%= t('billboard.new.head') %></h2>
<%= form_for :billboard, html: {miltipart: true}, url: billboards_path do |f| %>
  <%= render partial: "form", locals: {f: f} %>
<% end %>

app/views/billboards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render "billboard", billboard: @billboard %>
      <%= image_tag @billboard.photo.url if @billboard.photo? %>

      <div>
        <h2><%= t("comment.title") %></h2>
        <div class="row" id="row-main">
          <%= render @billboard.comments %>
        </div>
      </div>
      <div id="new-comment">
        <%= link_to image_tag("/add.png", size: "25x25"), new_billboard_comment_path(@billboard),
                    remote: true if user_signed_in? %>
      </div>
    </div>
    <div class="col-5">
      <div id="new-employment">
        <%= link_to t("billboard.show.request"),
                    new_billboard_billboard_employment_path(@billboard), remote: true if user_signed_in? %>
      </div>
    </div>
  </div>
</div>