config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, controllers: {
        confirmations: 'confirmations'
    }
    root 'billboards#index', as: 'home'
    resources :billboards do
      resources :billboard_employments
      resources :comments
    end
    resource :profile
    namespace :admin do
      # member do
      get 'billboards'
      get 'users'
      patch 'appoint_admin'
      patch 'remove_admin'
      patch 'confirm'
      # end
    end
  end
end

app/views/layouts/_admin_panel.html.erb
<div class="btn-group navbar-brand pr-5" role="group">
  <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" style=" margin-left: 50%;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= t("application.admin_menu") %>
  </button>
  <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    <link class="dropdown-item"><%= link_to t("application.new_billboard"), new_billboard_path,
                                            {:style => 'color:#808080;', :class => "alert-link ", :remote => false} %>
    <link class="dropdown-item"><%= link_to t("application.users"), admin_users_path,
                                            {:style => 'color:#808080;', :class => "alert-link ", :remote => false} %>
    <link class="dropdown-item"><%= link_to t("application.employments"), admin_billboards_path,
                                            {:style => 'color:#808080;', :class => "alert-link ", :remote => false} %>
  </div>
</div>

app/views/layouts/_user_panel.html.erb
<div class="btn-group navbar-brand pr-5" role="group">
  <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" style=" margin-left: 50%;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= t("application.menu") %>
  </button>
  <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    <link class="dropdown-item"><%= link_to t("application.profile"), profile_path,
                                            {:style => 'color:#808080;', :class => "alert-link"} %>
    <link class="dropdown-item"><%= link_to t("application.settings"), edit_profile_path,
                                            {:style => 'color:#808080;', :class => "alert-link"} %>
    <link class="dropdown-item"><%= link_to t("application.sign_out"), destroy_user_session_path,
                                            {:style => 'color:#808080;', :class => "alert-link", :method => :delete} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("application.head") %></title>
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.filestyle/1.1.0/js/bootstrap-filestyle.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <style type="text/css">
    A:hover {
      background: transparent;
    }
  </style>
</head>

<body>

<nav class="navbar navbar-dark bg-dark">
  <h5 class="navbar-brand ">
    <%= link_to image_tag("main.png", size: "35x35"), home_path, {:style => 'color:CC;', :class => "alert-link"} %>
  </h5>
  <%= render "layouts/admin_panel" if user_signed_in? and current_user.admin %>
  <% if user_signed_in? %>
  <%= render "layouts/user_panel" %>
  <% else %>
    <h6><%= link_to t("application.log_in"), new_user_session_path, {:style => 'color:	#C0C0C0;', :class => "alert-link"} %></h6>
  <% end %>
</nav>
<h4 style="background: #3CB371">
  <%= notice %>
  <%= alert %>
</h4>
<br>
<div class="container">
  <%= yield %>
</div>
<footer class="my-5 pt-5 ">
  <hr>
  <div class="text-muted text-center text-small">
    <p class="mb-1">&copy; 2019 Billboards</p>
  </div>
</footer>

</body>
</html>